baseURL = "https://mayosuke.jp/"
languageCode = "ja-jp"
title = "mayosuke.jp"
author = "Yosuke Miyajima"
copyright = "2017 Yosuke Miyajima"
googleanalytics = ""

[params]
  logo      = "/images/mayosuke.jpg"
  twitter   = "https://twitter.com/mayosuke"
  facebook  = "https://www.facebook.com/yosuke.miyajima"
  github    = "https://github.com/mayosuke/"
  devio     = "https://dev.classmethod.jp/author/miyajima-yosuke/"
  email     = "mayo.suke@gmail.com"
